column_mapping = {
    "Timestamp [Local]": "EventTimestamp",
    "Category": "Category",
    "Event Type [*]": "EventType",
    "Area": "Area",
    "Node": "Node",
    "Unit": "Unit",
    "Module": "Module",
    "Module Description": "ModuleDescription",
    "Parameter": "Parameter",
    "State": "State",
    "Level": "Level",
    "Desc1": "Description1",
    "Desc2": "Description2",
}
